http:
  routers:
    gateway:
      entrypoints:
        - web-secure
      rule: Host(`gateway.andronics.io`)
      service: gateway
  services:
    gateway:
      loadBalancer:
        servers:
          - url: http://192.168.1.254

