http:
  routers:
    gateway:
      entrypoints:
        - web-secure
      rule: Host(`printer.andronics.io`)
      service: printer
  services:
    printer:
      loadBalancer:
        servers:
          - url: http://192.168.0.252

