# https://docs.n8n.io/hosting/configuration/environment-variables/endpoints/

version: "3.9"

services:

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    environment:
      WEBHOOK_URL: https://n8n.andronics.io
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.n8n.entrypoints: web-secure
      traefik.http.services.n8n.loadbalancer.passHostHeader: true
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./config:/home/node/.n8n

networks:
  backend:
    external: true