version: "3.9"

services:
  tor:
    image: peterdavehello/tor-socks-proxy:latest
    container_name: tor
    dns:
      - 1.1.1.1
      - 8.8.4.4
      - 8.8.8.8
    healthcheck:
      test: ["CMD-SHELL","echo", "1"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      traefik.enable: false
      traefik.tcp.routers.tor.entrypoints: tor
      traefik.tcp.routers.tor.rule: HostSNI(`tor.andronics.io`)
      traefik.tcp.routers.tor.service: tor
      traefik.tcp.routers.tor.tls.certresolver: production
      traefik.tcp.routers.tor.tls.domains[0].main: tor.andronics.io
      traefik.tcp.services.tor.loadbalancer.server.port: 9050
    networks:
      - tor
    ports:
      - 9050:9050
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./config:/etc/tor
      - ./data:/var/lib/tor
      - /etc/localtime:/etc/localtime:ro

networks:
  tor:
    external: true