version: "3.9"

services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    environment:
      NODE_RED_ENABLE_PROJECTS: true
      NODE_RED_ENABLE_SAFE_MODE: false
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.nodered.entrypoints: web-secure
      traefik.http.services.nodered.loadbalancer.passHostHeader: true
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./data:/data

networks:
  backend:
    external: true
    

      
      