version: "3.9"

services:
  
  calibre:
    image: ghcr.io/linuxserver/calibre-web:latest
    container_name: calibre
    depends_on:
      - calibre-backend
    environment:
      DOCKER_MODS: ghcr.io/linuxserver/mods:universal-calibre
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1 
      PGID: 1000
      PUID: 1000
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.calibre-web.entrypoints: web-secure
      traefik.http.services.calibre-web.loadbalancer.passHostHeader: true
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./web:/config
      - /mnt/media:/mnt/media

  calibre-backend:
    image: ghcr.io/linuxserver/calibre:latest
    container_name: calibre-backend
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/London
    labels:
      traefik.enable: false
      traefik.http.routers.calibre.entrypoints: web-secure
      traefik.http.services.calibre.loadbalancer.passHostHeader: true
      traefik.http.services.calibre.loadbalancer.backend.port: 8080
    networks:
      - backend
    restart: unless-stopped
    security_opt:
      - "seccomp=unconfined"
    volumes:
      - ./server:/config
      - /mnt/media:/mnt/media
      
networks:
  backend:
    external: true