version: "3.9"

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.tcp.routers.mariadb.entrypoints: mariadb
      traefik.tcp.routers.mariadb.service: mariadb
      traefik.tcp.routers.mariadb.tls.certresolver: production
      traefik.tcp.routers.mariadb.tls.domains[0].main: mariadb.andronics.io
      traefik.tcp.services.mariadb.loadbalancer.server.port: 3306
    networks:
      - backend
    restart: unless-stopped
    secrets:
      - mariadb_root_password
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/docker-entrypoint.initdb.d:/docker-entrypoint.initdb.d

networks:
  backend:
    external: true

secrets:
  mariadb_root_password:
    file: /mnt/vault/secrets/mariadb/root_password