version: "3.9"

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: false
      LOG_LEVEL: info
      TZ: Europe/London
    labels:
      traefik.enable: false
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    external: true