version: "3.9"

services:
  wireguard:
    image: weejewel/wg-easy
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      WG_HOST: wireguard.andronics.io
    labels:
      traefik.enable: true
      traefik.http.routers.wireguard.entrypoints: web-secure
      traefik.http.services.wireguard.loadbalancer.passHostHeader: true
      traefik.http.services.wireguard.loadbalancer.server.port: 51821
      traefik.udp.routers.wireguard.entrypoints: wireguard
      traefik.udp.services.wireguard.loadbalancer.server.port: 51820
    networks:
      - backend
    restart: unless-stopped
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - ./etc:/etc/wireguard
    
networks:
  backend:
    external: true
    

      
      