version: "3.9"

services:

  mongo:
    image: mongo:7.0
    container_name: mongo
    command:
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_admin_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_admin_password
      TZ: Europe/London
    labels:
      traefik.enable: false
      traefik.tcp.routers.mongo.entrypoints: mongo
      traefik.tcp.routers.mongo.rule: HostSNI(`mongo.andronics.io`)
      traefik.tcp.routers.mongo.service: mongo
      traefik.tcp.routers.mongo.tls.certresolver: production
      traefik.tcp.routers.mongo.tls.domains[0].main: mongo.andronics.io
      traefik.tcp.services.mongo.loadbalancer.server.port: 27017
    networks:
      - backend
    restart: unless-stopped
    secrets:
      - mongo_admin_password
      - mongo_admin_username
    # user: 1000:1000
    volumes:
      - ./data/backup:/data/backup
      - ./data/db:/data/db
      - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

networks:
  backend:
    external: true

secrets:
  mongo_admin_password:
    file: /mnt/vault/secrets/mongo/admin_password
  mongo_admin_username:
    file: /mnt/vault/secrets/mongo/admin_username